### ISSUE TITLE
Authentication Issue with dockurr/samba (or dperson/samba)

### ISSUE THREAD

**Issue by Ashcora** [drudge/n8n-nodes-smb2#1]
First of all: **Thank you** for making SMB-Access possible using n8n 🥳 

**Description:**
When using **n8n-nodes-smb2** to connect to a Samba server running inside a **dockurr/samba:latest** container, authentication fails with the following error in the Samba logs:

```
create_connection_session_info: guest user (from session setup) not permitted to access this share (Druckerablage)
make_connection_snum: create_connection_session_info failed: NT_STATUS_ACCESS_DENIED
```

This suggests that the node is either not passing the credentials correctly or the authentication is defaulting to a guest session despite valid credentials being provided.

**Steps to Reproduce:**
1. Set up a Samba server using `dockurr/samba:latest` with the following `docker-compose.yml`:
    ```yaml
    services:
      samba:
        image: dockurr/samba:latest
        container_name: samba
        network_mode: bridge
        environment:
          NAME: "Druckerablage"
          USER: "Drucker"
          PASS: "password123"
        ports:
          - "445:445"
          - "139:139"
        volumes:
          - /opt/samba/mnt:/mnt:rw
          - /opt/samba/smb.conf:/etc/samba/smb.conf
        restart: always
    ```
2. Configure Samba with the following `smb.conf`:
    ```ini
    [global]
       security = user
       map to guest = never
       workgroup = WORKGROUP
       server role = standalone server
       client max protocol = default
       client min protocol = SMB2_02
       server max protocol = SMB3
       server min protocol = SMB2_02

    
    [Druckerablage]
       path = /mnt
       browseable = yes
       writable = yes
       guest ok = no
       valid users = Drucker
    ```
3. Attempt to connect via **n8n-nodes-smb2** using these credentials and parameters:
    - **Server:** `192.168.xxx.yyy`
    - **Username:** `WORKGROUP\Drucker` (or: `WORKGROUP/Drucker` but NOT with putting `WORKGROUP` to **Domain**)
    - **Password:** `password123`
    - **Domain:** ``
    - **Share Name:** `Druckerablage`
    - **Operation:** `List`
    - **Folder:** `/`

**Expected Behavior:**
The connection should succeed as it does when tested via `smbclient` from a VM running Ubuntu:
```
smbclient //192.168.xxx.yyy/Druckerablage -U WORKGROUP/Drucker
```

**Actual Behavior:**
n8n fails with the error:
```
Failed to connect to SMB server: File/Path Not Found (Code: 3221225506)
```
and the Samba logs show:
```
create_connection_session_info: guest user (from session setup) not permitted to access this share (Druckerablage)
make_connection_snum: create_connection_session_info failed: NT_STATUS_ACCESS_DENIED
```

**Additional Information:**
- When connecting to a **QNAP SMB Server** using the same node setup, authentication works correctly (also using WORKGROUP).
- The issue seems specific to the `dockurr/samba:latest` (or dperson/samba:latest) container, suggesting that **n8n-nodes-smb2** might not be handling authentication properly in some Samba environments.
- Removing `WORKGROUP\` from the username in n8n results in a **Logon Failure** error instead.
